data1 <- read.csv("C:/Users/JeetsPC-1/Desktop/Study Material/R DataSets/household_power_consumption.txt", header=TRUE, sep=";")
data1$Date=dmy(data1$Date)
data<-data1[(data1$Date >= "2007-02-01") & (data1$Date <= "2007-02-02"),]
data$Moment=as.POSIXct(paste(data$Date, data$Time), format="%Y-%m-%d %H:%M:%S")
data$Sub_metering_1=as.numeric(data$Sub_metering_1)
data$Sub_metering_2=as.numeric(data$Sub_metering_2)
data$Sub_metering_3=as.numeric(data$Sub_metering_3)
data$Global_reactive_power=as.numeric(data$Global_reactive_power)
data$Voltage=as.numeric(data$Voltage)
data$Global_active_power=as.numeric(data$Global_active_power)
par(mfrow=c(2,2))
plot(data$Moment,data$Global_active_power,type = "l",lty=1,ylab="Global Active Power (kilowatts)")
plot(data$Moment,data$Voltage,type = "l",lty=1,ylab="Voltage",xlab="datetime")
plot(data$Moment,data$Sub_metering_1,type = "l",lty=1,ylab="Energy Sub Metering")
lines(data$Moment,data$Sub_metering_2,type="l",lty=1,col="red")
lines(data$Moment,data$Sub_metering_3,type = "l",lty=1,col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty=1,cex = 0.25)

plot(data$Moment,data$Global_reactive_power,type = "l",lty=1,ylab="global_reactive_power",xlab="datetime")
